# Generated by Django 3.2.16 on 2024-11-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20241117_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='image',
        ),
    ]
